version: "3"
services:
  nginx:
    build: ./third_party_services/nginx
    ports:
      - 8888:80
    volumes:
      - ./public/:/app/public/
    env_file:
      - ./.env
    depends_on:
      - app
  app:
    build: .
    ports:
      - 8000
    volumes:
      - ./public/:/app/public/
      - ./logs/:/app/logs/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_docker_db
  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  postgres_data:
