# Generated by Django 3.1 on 2021-02-24 12:46

import companies.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='boolean_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='boolean_7',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_2',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_3',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_4',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='integer_1',
            field=models.IntegerField(default=companies.models.generate_test_int_field),
        ),
        migrations.AddField(
            model_name='company',
            name='integer_2',
            field=models.IntegerField(default=companies.models.generate_test_int_field),
        ),
        migrations.AddField(
            model_name='company',
            name='integer_3',
            field=models.IntegerField(default=companies.models.generate_test_int_field),
        ),
        migrations.AddField(
            model_name='company',
            name='integer_4',
            field=models.IntegerField(default=companies.models.generate_test_int_field),
        ),
        migrations.AddField(
            model_name='company',
            name='integer_5',
            field=models.IntegerField(default=companies.models.generate_test_int_field),
        ),
        migrations.AddField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
