# Generated by Django 3.1 on 2021-02-24 12:58

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210224_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='string_1',
            field=models.CharField(default=companies.models.generate_test_char_field, max_length=110),
        ),
        migrations.AddField(
            model_name='company',
            name='string_2',
            field=models.CharField(default=companies.models.generate_test_char_field, max_length=110),
        ),
        migrations.AddField(
            model_name='company',
            name='string_3',
            field=models.CharField(default=companies.models.generate_test_char_field, max_length=110),
        ),
        migrations.AddField(
            model_name='company',
            name='string_4',
            field=models.CharField(default=companies.models.generate_test_char_field, max_length=110),
        ),
        migrations.AddField(
            model_name='company',
            name='string_5',
            field=models.CharField(default=companies.models.generate_test_char_field, max_length=110),
        ),
    ]
