# Generated by Django 3.1 on 2021-02-24 13:22

from django.db import migrations, models
import django.db.models.deletion
import entities.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_auto_20210224_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=entities.models.generate_test_char_field, max_length=100, verbose_name='название')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('boolean_1', models.BooleanField(default=True)),
                ('boolean_2', models.BooleanField(default=True)),
                ('boolean_3', models.BooleanField(default=True)),
                ('boolean_4', models.BooleanField(default=False)),
                ('boolean_5', models.BooleanField(default=True)),
                ('boolean_6', models.BooleanField(default=False)),
                ('boolean_7', models.BooleanField(default=True)),
                ('integer_1', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_2', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_3', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_4', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_5', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('date_1', models.DateTimeField(auto_now=True)),
                ('date_2', models.DateTimeField(auto_now=True)),
                ('date_3', models.DateTimeField(auto_now=True)),
                ('date_4', models.DateTimeField(auto_now=True)),
                ('string_1', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_2', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_3', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_4', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_5', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities_objects', to='companies.company')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.CreateModel(
            name='SubObjectTypeTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=entities.models.generate_test_char_field, max_length=100, verbose_name='название')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('boolean_1', models.BooleanField(default=True)),
                ('boolean_2', models.BooleanField(default=True)),
                ('boolean_3', models.BooleanField(default=True)),
                ('boolean_4', models.BooleanField(default=False)),
                ('boolean_5', models.BooleanField(default=True)),
                ('boolean_6', models.BooleanField(default=False)),
                ('boolean_7', models.BooleanField(default=True)),
                ('integer_1', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_2', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_3', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_4', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_5', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('date_1', models.DateTimeField(auto_now=True)),
                ('date_2', models.DateTimeField(auto_now=True)),
                ('date_3', models.DateTimeField(auto_now=True)),
                ('date_4', models.DateTimeField(auto_now=True)),
                ('string_1', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_2', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_3', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_4', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_5', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objects', to='companies.company')),
            ],
            options={
                'verbose_name': 'под-объект-2-тип',
                'verbose_name_plural': 'под-объекты-2-тип',
            },
        ),
        migrations.CreateModel(
            name='SubObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=entities.models.generate_test_char_field, max_length=100, verbose_name='название')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('boolean_1', models.BooleanField(default=True)),
                ('boolean_2', models.BooleanField(default=True)),
                ('boolean_3', models.BooleanField(default=True)),
                ('boolean_4', models.BooleanField(default=False)),
                ('boolean_5', models.BooleanField(default=True)),
                ('boolean_6', models.BooleanField(default=False)),
                ('boolean_7', models.BooleanField(default=True)),
                ('integer_1', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_2', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_3', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_4', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('integer_5', models.IntegerField(default=entities.models.generate_test_int_field)),
                ('date_1', models.DateTimeField(auto_now=True)),
                ('date_2', models.DateTimeField(auto_now=True)),
                ('date_3', models.DateTimeField(auto_now=True)),
                ('date_4', models.DateTimeField(auto_now=True)),
                ('string_1', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_2', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_3', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_4', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('string_5', models.CharField(default=entities.models.generate_test_char_field, max_length=100)),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_objects', to='entities.object')),
            ],
            options={
                'verbose_name': 'под-объект',
                'verbose_name_plural': 'под-объекты',
            },
        ),
    ]
